services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../backend:/workspace/backend:cached
      - ../frontend:/workspace/frontend:cached
    working_dir: /workspace
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=fscs
      - DB_PASSWORD=fscs    
    networks:
      - fscs-network
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    depends_on:
      - laravel
      - react
      - mysql

  laravel:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: laravel:11
    volumes:
      - ./backend/php.ini:/usr/local/etc/php/php.ini
      - ../backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=fscs
      - DB_PASSWORD=fscs
    depends_on:
      - mysql
    networks:
      - fscs-network

  # Nginx Server
  laravel-nginx:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ../backend:/var/www/html
    depends_on:
      - laravel
    networks:
      - fscs-network

  react:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/usr/share/nginx/html
    networks:
      - fscs-network

  react-nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  
      - ../frontend/:/usr/share/nginx/html/
    depends_on: 
      - react
    ports:
      - "82:80"
    networks:
      - fscs-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: fscs
      MYSQL_PASSWORD: fscs
    networks:
      - fscs-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: fscs
      PMA_PASSWORD: fscs
    depends_on: 
      - mysql
    networks:
      - fscs-network

networks:
  fscs-network:
