services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devcontainer
    volumes:
      - ../backend:/workspace/backend:cached
      - ../frontend:/workspace/frontend:cached
    working_dir: /workspace
    networks:
      - fscs-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=fscs
      - DB_PASSWORD=fscs
    depends_on:
      - mysql

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/var/www/html
      - ./backend/php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=fscs
      - DB_PASSWORD=fscs
    depends_on:
      - mysql      
    networks:
      - fscs-network

  backend-nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "81:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/nginx.conf
      - ../backend:/var/www/html
    depends_on:
      - backend
    networks:
      - fscs-network      

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend:/usr/share/nginx/html
  #   networks:
  #     - fscs-network

  frontend-nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf  
      - ../frontend/:/usr/share/nginx/html/
    ports:
      - "82:80"
    networks:
      - fscs-network

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: fscs
      MYSQL_PASSWORD: fscs
    networks:
      - fscs-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: fscs
      PMA_PASSWORD: fscs
    networks:
      - fscs-network

networks:
  fscs-network:
